"""Alert inspection tools for DATT AI Agent."""

from datetime import datetime, timezone
from typing import Any
from uuid import UUID

from langchain_core.tools import tool
from sqlalchemy import func, or_, select

from src.agent.config import agent_config
from src.agent.tools.notification_queries import filtered_notifications, status_totals
from src.cameras.service import database
from src.db.models import Camera, FaceEvent, Notification, PlateEvent, Target, VehicleWatchlist
from src.notifications.alerts import EVENT_TYPES, camera_aliases
from src.notifications.errors import ERROR_MESSAGES, safe_error


@tool
def get_alerts(
    camera_id: str | None = None,
    status: str | None = None,
    event_type: str | None = None,
    start_time: str | None = None,
    from_time: str | None = None,
    end_time: str | None = None,
    to_time: str | None = None,
    target_name: str | None = None,
    plate_number: str | None = None,
    search: str | None = None,
    limit: int = 20,
    event_id: str | None = None,
    target_id: str | None = None,
) -> dict[str, Any]:
    """Retrieve operational alerts generated by face and vehicle watchlist matches.

    Distinguishes:
    1. Watchlist match alerts (Notification projection) vs general recognition events.
    2. Stored alert lifecycle status: 'pending' (unprocessed/awaiting delivery), 'sent', 'failed', 'suppressed' (cooldown).
       Note: The current schema does not persist separate 'acknowledged' or 'resolved' states.
    3. Breakdown by camera, status, and event type.

    Args:
        camera_id: Optional camera identifier or UUID.
        status: Optional alert status: 'pending', 'sent', 'failed', 'suppressed', or 'all'.
        event_type: Optional alert type: 'FACE_WATCHLIST_MATCH', 'VEHICLE_WATCHLIST_MATCH', or 'all'.
        start_time: Optional start ISO timestamp / date.
        from_time: Optional alias for start_time.
        end_time: Optional end ISO timestamp / date.
        to_time: Optional alias for end_time.
        target_name: Optional person name or vehicle display name.
        plate_number: Optional vehicle license plate.
        search: Optional text search query across target, plate, recipient, or camera.
        limit: Maximum number of alerts to return (1-100, default 20).

    Returns:
        Structured alert records, status breakdown, event type breakdown, and busiest alert cameras.
    """
    bounded_limit = max(1, min(100, limit))
    eff_start = start_time or from_time
    eff_end = end_time or to_time

    db = None
    try:
        db = agent_config.get_database()
        with db.transaction() as session:
            q = filtered_notifications(session, camera_id=camera_id, status=status, event_type=event_type,
                event_id=event_id, target_id=target_id, target_name=target_name, plate_number=plate_number,
                search=search, start_time=eff_start, end_time=eff_end)
            filtered = q.subquery()

            total = session.scalar(select(func.count()).select_from(q.subquery())) or 0

            # Execute query ordered by created_at desc
            q_exec = q.order_by(Notification.created_at.desc(), Notification.id.desc()).limit(bounded_limit)
            rows = session.execute(q_exec).all()

            # Batch resolve camera display labels
            keys = {r[0].camera_id for r in rows if r[0].camera_id}
            ids = []
            for key in keys:
                try:
                    ids.append(UUID(key))
                except ValueError:
                    pass
            cams = session.scalars(select(Camera).where(or_(Camera.registry_key.in_(keys), Camera.id.in_(ids)))).all() if keys else []
            names = {}
            locations = {}
            for cam in cams:
                for k in (cam.registry_key, str(cam.id), cam.id.hex):
                    if k:
                        names[k] = cam.name
                        locations[k] = cam.location

            alerts = []
            for item, face, plate, target, vehicle in rows:
                is_face = item.event_id is not None
                e_type = "FACE_WATCHLIST_MATCH" if is_face else "VEHICLE_WATCHLIST_MATCH"
                target_label = target.name if target else (vehicle.display_name if vehicle else None)
                plate_label = (plate.normalized_plate or plate.plate_text) if plate else None
                camera_name = names.get(item.camera_id) or item.camera_id

                alerts.append({
                    "id": str(item.id),
                    "event_type": e_type,
                    "status": item.status,
                    "camera_id": item.camera_id,
                    "camera_name": camera_name,
                    "camera_location": locations.get(item.camera_id),
                    "target_name": target_label,
                    "plate_number": plate_label,
                    "created_at": item.created_at.isoformat() if item.created_at else None,
                    "sent_at": item.sent_at.isoformat() if item.sent_at else None,
                    "retry_count": item.retry_count,
                    "error": safe_error(item.error) if item.error else None,
                })

            # Every summary uses the same unpaginated filtered relation as the displayed records.
            status_counts = status_totals(session, filtered)
            cam_stmt = (select(filtered.c.camera_id, func.count()).group_by(filtered.c.camera_id)
                        .order_by(func.count().desc(), filtered.c.camera_id).limit(5))
            top_cams = [{"camera_id": str(camera), "alert_count": int(count)}
                        for camera, count in session.execute(cam_stmt)]

            return {
                "status": "success",
                "total_alerts": total,
                "count": len(alerts),
                "status_breakdown": status_counts,
                "pending_alerts_count": status_counts.get("pending", 0),
                "sent_alerts_count": status_counts.get("sent", 0),
                "failed_alerts_count": status_counts.get("failed", 0),
                "suppressed_alerts_count": status_counts.get("suppressed", 0),
                "top_cameras_by_alerts": top_cams,
                "alerts": alerts,
                "schema_note": (
                    "Lưu ý mô hình CSDL Alert Center: Cảnh báo phát sinh từ sự kiện trùng khớp Watchlist (Notification projection). "
                    "Các trạng thái được lưu trữ: 'pending' (chưa xử lý/chờ gửi), 'sent' (đã gửi), 'failed' (lỗi), 'suppressed' (hạn chế lặp). "
                    "Hệ thống không lưu trữ trạng thái 'acknowledged' hay 'resolved' riêng biệt."
                ),
            }
    except Exception as exc:
        return {"status": "error", "message": "Không thể truy xuất cảnh báo hoặc bộ lọc không hợp lệ; chưa xác minh được số lượng."}
    finally:
        if db is not None:
            db.dispose()
