"""Alert inspection tools for DATT AI Agent."""

from datetime import datetime, timezone
from typing import Any
from uuid import UUID

from langchain_core.tools import tool
from sqlalchemy import func, or_, select

from src.agent.config import agent_config
from src.agent.tools.analytics import parse_iso_time
from src.cameras.service import database
from src.db.models import Camera, FaceEvent, Notification, PlateEvent, Target, VehicleWatchlist
from src.notifications.alerts import EVENT_TYPES, camera_aliases
from src.notifications.errors import ERROR_MESSAGES, safe_error


@tool
def get_alerts(
    camera_id: str | None = None,
    status: str | None = None,
    event_type: str | None = None,
    start_time: str | None = None,
    from_time: str | None = None,
    end_time: str | None = None,
    to_time: str | None = None,
    target_name: str | None = None,
    plate_number: str | None = None,
    search: str | None = None,
    limit: int = 20,
) -> dict[str, Any]:
    """Retrieve operational alerts generated by face and vehicle watchlist matches.

    Distinguishes:
    1. Watchlist match alerts (Notification projection) vs general recognition events.
    2. Stored alert lifecycle status: 'pending' (unprocessed/awaiting delivery), 'sent', 'failed', 'suppressed' (cooldown).
       Note: The current schema does not persist separate 'acknowledged' or 'resolved' states.
    3. Breakdown by camera, status, and event type.

    Args:
        camera_id: Optional camera identifier or UUID.
        status: Optional alert status: 'pending', 'sent', 'failed', 'suppressed', or 'all'.
        event_type: Optional alert type: 'FACE_WATCHLIST_MATCH', 'VEHICLE_WATCHLIST_MATCH', or 'all'.
        start_time: Optional start ISO timestamp / date.
        from_time: Optional alias for start_time.
        end_time: Optional end ISO timestamp / date.
        to_time: Optional alias for end_time.
        target_name: Optional person name or vehicle display name.
        plate_number: Optional vehicle license plate.
        search: Optional text search query across target, plate, recipient, or camera.
        limit: Maximum number of alerts to return (1-100, default 20).

    Returns:
        Structured alert records, status breakdown, event type breakdown, and busiest alert cameras.
    """
    bounded_limit = max(1, min(100, limit))
    eff_start = start_time or from_time
    eff_end = end_time or to_time
    eff_search = search or target_name or plate_number

    db = agent_config.get_database()
    try:
        with db.transaction() as session:
            q = (
                select(Notification, FaceEvent, PlateEvent, Target, VehicleWatchlist)
                .outerjoin(FaceEvent, Notification.event_id == FaceEvent.id)
                .outerjoin(PlateEvent, Notification.plate_event_id == PlateEvent.id)
                .outerjoin(Target, FaceEvent.target_id == Target.id)
                .outerjoin(VehicleWatchlist, Notification.vehicle_watchlist_id == VehicleWatchlist.id)
            )

            # Status filter
            if status and status.lower() != "all":
                st_clean = status.lower().strip()
                if st_clean in ("pending", "sent", "failed", "suppressed"):
                    q = q.where(Notification.status == st_clean)

            # Event type filter
            if event_type and event_type != "all":
                et_clean = event_type.strip().upper()
                if et_clean == "FACE_WATCHLIST_MATCH":
                    q = q.where(Notification.event_id.is_not(None))
                elif et_clean == "VEHICLE_WATCHLIST_MATCH":
                    q = q.where(Notification.plate_event_id.is_not(None))

            # Camera filter
            if camera_id and camera_id != "all":
                q = q.where(Notification.camera_id.in_(camera_aliases(camera_id.strip())))

            # Time filters
            if eff_start:
                try:
                    start_dt = parse_iso_time(eff_start, datetime.min.replace(tzinfo=timezone.utc))
                    q = q.where(Notification.created_at >= start_dt)
                except Exception:
                    pass
            if eff_end:
                try:
                    end_dt = parse_iso_time(eff_end, datetime.max.replace(tzinfo=timezone.utc))
                    q = q.where(Notification.created_at <= end_dt)
                except Exception:
                    pass

            # Search filter
            if eff_search and eff_search.strip():
                s_like = f"%{eff_search.strip()}%"
                q = q.where(
                    or_(
                        Target.name.ilike(s_like),
                        VehicleWatchlist.display_name.ilike(s_like),
                        VehicleWatchlist.plate_number.ilike(s_like),
                        PlateEvent.plate_text.ilike(s_like),
                        PlateEvent.normalized_plate.ilike(s_like),
                        Notification.recipient.ilike(s_like),
                        Notification.camera_id.ilike(s_like),
                    )
                )

            total = session.scalar(select(func.count()).select_from(q.subquery())) or 0

            # Execute query ordered by created_at desc
            q_exec = q.order_by(Notification.created_at.desc(), Notification.id.desc()).limit(bounded_limit)
            rows = session.execute(q_exec).all()

            # Batch resolve camera display labels
            keys = {r[0].camera_id for r in rows if r[0].camera_id}
            ids = []
            for key in keys:
                try:
                    ids.append(UUID(key))
                except ValueError:
                    pass
            cams = session.scalars(select(Camera).where(or_(Camera.registry_key.in_(keys), Camera.id.in_(ids)))).all() if keys else []
            names = {}
            locations = {}
            for cam in cams:
                for k in (cam.registry_key, str(cam.id), cam.id.hex):
                    if k:
                        names[k] = cam.name
                        locations[k] = cam.location

            alerts = []
            for item, face, plate, target, vehicle in rows:
                is_face = item.event_id is not None
                e_type = "FACE_WATCHLIST_MATCH" if is_face else "VEHICLE_WATCHLIST_MATCH"
                target_label = target.name if target else (vehicle.display_name if vehicle else None)
                plate_label = (plate.normalized_plate or plate.plate_text) if plate else None
                camera_name = names.get(item.camera_id) or item.camera_id

                alerts.append({
                    "id": str(item.id),
                    "event_type": e_type,
                    "status": item.status,
                    "camera_id": item.camera_id,
                    "camera_name": camera_name,
                    "camera_location": locations.get(item.camera_id),
                    "target_name": target_label,
                    "plate_number": plate_label,
                    "created_at": item.created_at.isoformat() if item.created_at else None,
                    "sent_at": item.sent_at.isoformat() if item.sent_at else None,
                    "retry_count": item.retry_count,
                    "error": safe_error(item.error) if item.error else None,
                })

            # Calculate aggregated breakdown
            status_stmt = select(Notification.status, func.count(Notification.id))
            if eff_start or eff_end or camera_id:
                sub_where = []
                if camera_id and camera_id != "all":
                    sub_where.append(Notification.camera_id.in_(camera_aliases(camera_id.strip())))
                if eff_start:
                    try:
                        sub_where.append(Notification.created_at >= parse_iso_time(eff_start, datetime.min.replace(tzinfo=timezone.utc)))
                    except Exception:
                        pass
                if eff_end:
                    try:
                        sub_where.append(Notification.created_at <= parse_iso_time(eff_end, datetime.max.replace(tzinfo=timezone.utc)))
                    except Exception:
                        pass
                if sub_where:
                    status_stmt = status_stmt.where(*sub_where)
            status_counts = {str(r[0]): int(r[1]) for r in session.execute(status_stmt.group_by(Notification.status)).all()}

            # Camera alert ranking
            cam_stmt = select(Notification.camera_id, func.count(Notification.id)).group_by(Notification.camera_id).order_by(func.count(Notification.id).desc()).limit(5)
            top_cams = [{"camera_id": str(r[0]), "alert_count": int(r[1])} for r in session.execute(cam_stmt).all()]

            return {
                "status": "success",
                "total_alerts": total,
                "count": len(alerts),
                "status_breakdown": status_counts,
                "pending_alerts_count": status_counts.get("pending", 0),
                "sent_alerts_count": status_counts.get("sent", 0),
                "failed_alerts_count": status_counts.get("failed", 0),
                "suppressed_alerts_count": status_counts.get("suppressed", 0),
                "top_cameras_by_alerts": top_cams,
                "alerts": alerts,
                "schema_note": (
                    "Lưu ý mô hình CSDL Alert Center: Cảnh báo phát sinh từ sự kiện trùng khớp Watchlist (Notification projection). "
                    "Các trạng thái được lưu trữ: 'pending' (chưa xử lý/chờ gửi), 'sent' (đã gửi), 'failed' (lỗi), 'suppressed' (hạn chế lặp). "
                    "Hệ thống không lưu trữ trạng thái 'acknowledged' hay 'resolved' riêng biệt."
                ),
            }
    except Exception as exc:
        return {"status": "error", "message": f"Failed to retrieve alerts: {exc}"}
    finally:
        db.dispose()
